apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingapp
  labels:
    app: bankingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankingapp
  template:
    metadata:
      labels:
        app: bankingapp
    spec:
      containers:
      - name: bankingapp-container
        image: maddy2964/banking-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankingapp-service
  labels:
    app: bankingapp
spec:
  selector:
    app: bankingapp

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082